apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-ha-application-with-redis
  labels:
    app: kubernetes-test-ha-application-with-redis
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: kubernetes-test-ha-application-with-redis