apiVersion: v1
kind: Pod
metadata:
  name: application-pod
  namespace: pods-activity
spec:
  restartPolicy: OnFailure
  containers:
    - name: custom-application-container
      image: packtworkshops/the-kubernetes-workshop:custom-application-for-pods-chapter
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 20
        periodSeconds: 10