apiVersion: v1
kind: Pod
metadata:
  name: infra-libraries-application
  namespace: metadata-activity
  labels:
    environment: production
    team: infra-libraries
    critical: "true"
  annotations:
      team-link: "https://jira-link/team-link-2"
spec:
  containers:
  - name: application-container
    image: nginx
