kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: podlifecycleconfig-crd-view-binding
  namespace: crddemo
subjects:
- kind: ServiceAccount
  name: default
  namespace: crddemo
roleRef:
  kind: Role
  name: podlifecycleconfig-crd-view
  apiGroup: ""
  # rbac.authorization.k8s.io